---
namespace: compscidr
name: spotify
authors:
    - Jason Ernst <ernstjason1@gmail.com>
description: Installs spotify
license_file: LICENSE
readme: README.md
version: 0.0.4
repository: https://github.com/compscidr/ansible-spotify
tags:
    - spotify
    - application
